[package]
name = "usbio-rs"
version = "0.1.0"
edition = "2021"
authors = ["Ryo Yoshimitsu<ryoyoshimitsu@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3.0"